[project]
name = "meng-ya"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
venv=".venv"
requires-python = ">=3.14"
dependencies = [
    "audioop-lts>=0.2.2",
    "google-genai>=1.47.0",
    "py-cord>=2.6.1",
    "python-dotenv>=1.2.1",
]
